/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <quackmore-ff@yahoo.com> wrote this file.  As long as you retain this notice
 * you can do whatever you want with this stuff. If we meet some day, and you 
 * think this stuff is worth it, you can buy me a beer in return. Quackmore
 * ----------------------------------------------------------------------------
 */

// SDK includes
extern "C"
{
#include "mem.h"
}

#include "espbot_cron.hpp"
#include "espbot_global.hpp"
#include "app.hpp"
#include "app_relay.hpp"
#include "app_command.hpp"

/*
 *  APP_RELEASE is coming from git
 *  'git --no-pager describe --tags --always --dirty'
 *  and is generated by the Makefile
 */

#ifndef APP_RELEASE
#define APP_RELEASE "Unavailable"
#endif

char *app_release = APP_RELEASE;

char *app_name = "Smart Timer";

void app_init_before_wifi(void)
{
    // init_dio_task();
    // cron_add_job(CRON_STAR, CRON_STAR, CRON_STAR, CRON_STAR, CRON_STAR, temp_log_read);
    app_relay_init();
    app_command_init();
    // cron_add_job(CRON_STAR, CRON_STAR, CRON_STAR, CRON_STAR, CRON_STAR, NULL, NULL);
}

os_timer_t thermostat_start_timer;

void thermostat_start(void)
{
    cron_sync();
}

void app_init_after_wifi(void)
{
    static bool first_time = true;
    if (first_time)
    {
        first_time = false;
        os_timer_disarm(&thermostat_start_timer);
        os_timer_setfn(&thermostat_start_timer, (os_timer_func_t *)thermostat_start, NULL);
        os_timer_arm(&thermostat_start_timer, 2000, 0);
    }
}

void app_deinit_on_wifi_disconnect()
{
}