/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <quackmore-ff@yahoo.com> wrote this file.  As long as you retain this notice
 * you can do whatever you want with this stuff. If we meet some day, and you 
 * think this stuff is worth it, you can buy me a beer in return. Quackmore
 * ----------------------------------------------------------------------------
 */
#ifndef __APP_EVENT_CODES_H__
#define __APP_EVENT_CODES_H__

#define APP_GET_API_INFO_HEAP_EXHAUSTED 0x1180
#define APP_GET_COMMAND_HEAP_EXHAUSTED 0x1181
#define APP_POST_COMMAND_HEAP_EXHAUSTED 0x1182
#define APP_GET_COMMANDIDX_HEAP_EXHAUSTED 0x1183
#define APP_PUT_COMMANDIDX_HEAP_EXHAUSTED 0x1184
#define APP_GET_RELAY_HEAP_EXHAUSTED 0x1185
#define APP_GET_RELAY_IDX_HEAP_EXHAUSTED 0x1186
#define APP_PUT_RELAY_IDX_HEAP_EXHAUSTED 0x1187

#define RESTORE_RELAY_LIST_FS_NOT_AVAILABLE 0x1190
#define RESTORE_RELAY_LIST_INCOMPLETE 0x1191
#define SAVED_RELAY_LIST_NOT_UPDATED_FS_NOT_AVAILABLE 0x1192
#define SAVED_RELAY_LIST_NOT_UPDATED_INCOMPLETE 0x1193
#define REMOVE_RELAY_LIST_FS_NOT_AVAILABLE 0x1194
#define SAVE_RELAY_LIST_FS_NOT_AVAILABLE 0x1195
#define SAVE_RELAY_LIST_CANNOT_OPEN_FILE 0x1196

#define RESTORE_COMMAND_LIST_FS_NOT_AVAILABLE 0x11A0
#define RESTORE_COMMAND_LIST_INCOMPLETE 0x11A1
#define SAVED_COMMAND_LIST_NOT_UPDATED_FS_NOT_AVAILABLE 0x11A2
#define SAVED_COMMAND_LIST_NOT_UPDATED_INCOMPLETE 0x11A3
#define REMOVE_COMMAND_LIST_FS_NOT_AVAILABLE 0x11A4
#define SAVE_COMMAND_LIST_FS_NOT_AVAILABLE 0x11A5
#define SAVE_COMMAND_LIST_CANNOT_OPEN_FILE 0x11A6

#endif
