/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <quackmore-ff@yahoo.com> wrote this file.  As long as you retain this notice
 * you can do whatever you want with this stuff. If we meet some day, and you 
 * think this stuff is worth it, you can buy me a beer in return. Quackmore
 * ----------------------------------------------------------------------------
 */
#ifndef __APP_EVENT_CODES_H__
#define __APP_EVENT_CODES_H__

#define APP_GET_API_INFO_HEAP_EXHAUSTED 0x0A80
#define APP_GET_COMMAND_HEAP_EXHAUSTED 0x0A81
#define APP_POST_COMMAND_HEAP_EXHAUSTED 0x0A82
#define APP_GET_COMMANDIDX_HEAP_EXHAUSTED 0x0A83
#define APP_PUT_COMMANDIDX_HEAP_EXHAUSTED 0x0A84
#define APP_GET_RELAY_HEAP_EXHAUSTED 0x0A85
#define APP_GET_RELAY_IDX_HEAP_EXHAUSTED 0x0A86
#define APP_PUT_RELAY_IDX_HEAP_EXHAUSTED 0x0A87

#define RESTORE_RELAY_LIST_FS_NOT_AVAILABLE 0x0A90
#define RESTORE_RELAY_LIST_INCOMPLETE 0x0A91
#define SAVED_RELAY_LIST_NOT_UPDATED_FS_NOT_AVAILABLE 0x0A92
#define SAVED_RELAY_LIST_NOT_UPDATED_INCOMPLETE 0x0A93
#define REMOVE_RELAY_LIST_FS_NOT_AVAILABLE 0x0A94
#define SAVE_RELAY_LIST_FS_NOT_AVAILABLE 0x0A95
#define SAVE_RELAY_LIST_CANNOT_OPEN_FILE 0x0A96

#define RESTORE_COMMAND_LIST_FS_NOT_AVAILABLE 0x0AA0
#define RESTORE_COMMAND_LIST_INCOMPLETE 0x0AA1
#define SAVED_COMMAND_LIST_NOT_UPDATED_FS_NOT_AVAILABLE 0x0AA2
#define SAVED_COMMAND_LIST_NOT_UPDATED_INCOMPLETE 0x0AA3
#define REMOVE_COMMAND_LIST_FS_NOT_AVAILABLE 0x0AA4
#define SAVE_COMMAND_LIST_FS_NOT_AVAILABLE 0x0AA5
#define SAVE_COMMAND_LIST_CANNOT_OPEN_FILE 0x0AA6

#endif
